version: "3"
services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./dev:/code
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: ./docker/engine
        links:
            - db:mysql
        volumes:
            - ./dev:/code
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_DATABASE: symfony

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:mysql
        ports:
            - 76:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root

volumes:
    db_data:
